fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "%fos_user_email_address%"
        sender_name: "%fos_user_email_address%"
    service:
        user_manager: fos_user.user_manager.default
    registration:
        confirmation:
            enabled:    true # change to true for required email confirmation
            template:   FOSUserBundle:Registration:email.txt.twig