<?php

namespace App\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    public function getLatest($nb)
    {
        if ($nb < 1) $nb = 1;

        $q = $this->createQueryBuilder('n')
            ->orderBy('n.id', 'DESC')
            ->setMaxResults($nb);

        return $q->getQuery()->execute();
    }
}
