<?php

namespace InsaLan\TournamentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroupStageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupStageRepository extends EntityRepository
{
    protected function getQueryBuilder()
    {
        return $this->createQueryBuilder('gs')
        ;
    }
    public function getByTournament(Tournament $t)
    {
        $q = $this->getQueryBuilder();
        $q->where('gs.tournament = :t')->setParameter('t', $t);

        return $q->getQuery()->execute();
    }
}
