<?php

namespace InsaLan\TournamentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroupMatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupMatchRepository extends EntityRepository
{
  public function removeParticipant(Group $group, Participant $participant)
  {
    // Doctrine doesn't support joins in delete statements, so we have to do this in two steps
    $gm = $this->createQueryBuilder('gm')
      ->select('partial gm.{id}')
      ->leftJoin('gm.match', 'm')
      ->where('gm.group = :g')->setParameter('g', $group->getId())
      ->andWhere('m.part1 = :p OR m.part2 = :p')->setParameter('p', $participant->getId())
      ->getQuery()->getResult(\Doctrine\ORM\Query::HYDRATE_SCALAR);

    $ids = array_map(function($a) { return $a['gm_id']; }, $gm);
    if ($ids) {
      $this->createQueryBuilder('gm')
        ->delete()
        ->where('gm.id IN ('.implode(',', $ids).')')
        ->getQuery()->execute();
    }
  }
}
