services:
    sonata.admin.archives.picture:
        class: InsaLan\ArchivesBundle\Admin\PictureAlbumAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Archives", label: " Album photo" }
        arguments:
            - ~
            - InsaLan\ArchivesBundle\Entity\PictureAlbum
            - ~
        calls:
            - [ setTranslationDomain, [InsaLanArchivesBundle]]

    sonata.admin.archives.stream:
        class: InsaLan\ArchivesBundle\Admin\StreamAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Archives", label: "Stream" }
        arguments:
            - ~
            - InsaLan\ArchivesBundle\Entity\Stream
            - ~
        calls:
            - [ setTranslationDomain, [InsaLanArchivesBundle]]
