<?php

namespace App\Repository;

/**
 * LegalDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LegalDocumentRepository extends \Doctrine\ORM\EntityRepository
{
}
