<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsSliderRepository extends EntityRepository
{
    public function getLatest($nb)
    {
        if ($nb < 1) $nb = 1;

        $q = $this->createQueryBuilder('s')
            ->orderBy('s.id', 'DESC')
            ->setMaxResults($nb);

        return $q->getQuery()->execute();
    }
}
