<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StreamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StreamRepository extends EntityRepository
{
}
