<?php

namespace InsaLan\ArchivesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
* PictureRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class PictureRepository extends EntityRepository
{
	public function findPreviousYearPictures($year) {
		$query = $this->createQueryBuilder('t')
		->Where('t.date BETWEEN :start AND :end')
		->setParameter('start', new \Datetime($year.'-01-01'))
		->setParameter('end',   new \Datetime($year.'-12-31'))
		->orderBy('t.date', 'ASC')
		->getQuery();
		return $query->getResult();
	}

	public function findPreviousYearPicturesAlbum($year) {
		$query = $this->_em->createQuery('SELECT DISTINCT p.album FROM InsaLanArchivesBundle:Picture p WHERE p.date BETWEEN :start AND :end')
		->setParameter('start', new \Datetime($year.'-01-01'))
		->setParameter('end',   new \Datetime($year.'-12-31'));
		return $query->getScalarResult();
	}

	public function findPreviousYearPicturesByAlbum($year, $album) {
		$query = $this->createQueryBuilder('t')
		->Where('t.date BETWEEN :start AND :end')
		->setParameter('start', new \Datetime($year.'-01-01'))
		->setParameter('end',   new \Datetime($year.'-12-31'))
		->andWhere('t.album = :album')
		->setParameter('album',   $album)
		->orderBy('t.date', 'ASC')
		->getQuery();
		return $query->getResult();
	}
}
