<?php

namespace InsaLan\ArchivesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StreamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StreamRepository extends EntityRepository
{
	    public function findPreviousYearStreams($year) {
        $query = $this->createQueryBuilder('s')
            ->Where('s.date BETWEEN :start AND :end')
            ->setParameter('start', new \Datetime($year.'-01-01'))  
            ->setParameter('end',   new \Datetime($year.'-12-31'))  
            ->orderBy('s.date', 'ASC')
            ->getQuery();
        return $query->getResult();
    }
}
