<?php

namespace InsaLan\ArchivesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StreamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StreamRepository extends EntityRepository
{
	    public function findPreviousYearStreams($year) {
        $query = $this->createQueryBuilder('s')
            ->Where('s.date BETWEEN :start AND :end')
            ->setParameter('start', new \Datetime($year.'-01-01'))
            ->setParameter('end',   new \Datetime($year.'-12-31'))
            ->orderBy('s.date', 'ASC')
            ->getQuery();
        return $query->getResult();
    }

		public function findPreviousYearStreamsAlbum($year) {
			$query = $this->_em->createQuery('SELECT DISTINCT p.album FROM InsaLanArchivesBundle:Stream p WHERE p.date BETWEEN :start AND :end')
			->setParameter('start', new \Datetime($year.'-01-01'))
			->setParameter('end',   new \Datetime($year.'-12-31'));
			return $query->getResult();
		}

		public function findPreviousYearStreamsByAlbum($year, $album) {
			$query = $this->createQueryBuilder('t')
			->Where('t.date BETWEEN :start AND :end')
			->setParameter('start', new \Datetime($year.'-01-01'))
			->setParameter('end',   new \Datetime($year.'-12-31'))
			->andWhere('t.album = :album')
			->setParameter('album',   $album)
			->orderBy('t.date', 'ASC')
			->getQuery();
			return $query->getResult();
		}
}
