index:
    path: /
    controller: App\Controller\News*

tournament:
    path: /tournament
    controller: App\Controller\Tournament*

infos:
    path: /infos
    controller: App\Controller\Information*

pizza:
    path: /pizza
    controller: App\Controller\Pizza*

admin:
    path: /admin
    controller: App\Controller\Admin*

archives:
    path: /archives
    controller: App\Controller\Archives*

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

payum_all:
    resource: "@PayumBundle/Resources/config/routing/all.xml"
