index:
    path: /
    controller: App\Controller\News*

tournament:
    path: /tournament
    controller: App\Controller\Tournament*

infos:
    path: /infos
    controller: App\Controller\Information*

pizza:
    path: /pizza
    controller: App\Controller\Pizza*
