parameters:
    insalan.db.table_prefix: intra_

services:
    insalan.tblprefix_subscriber:
        class: InsaLan\InsaLanBundle\Subscriber\TablePrefixSubscriber
        arguments: [%insalan.db.table_prefix%]
        tags:
            - { name: doctrine.event_subscriber }
    insalan.free_slots:
        class: InsaLan\InsaLanBundle\Service\FreeSlots
        arguments: [@doctrine]
    insalan.opening_matcher:
        class: InsaLan\InsaLanBundle\Security\OpeningRequestMatcher